* create a function which can be used for login , can return True if called with correct credentials else return False
* create a function to generate factorials of a given number
* create a function which can count number of vowels used in the given string as argument

In [ ]:
def login(username, password):
    # Predefined correct credentials
    correct_username = "admin"
    correct_password = "password123"

    return username == correct_username and password == correct_password

In [ ]:
username = input("Enter User name")
userpass = input("Enter Password")

login(username, userpass)

Enter User nameadmin
Enter Passwordpassword123


True

In [ ]:
def factorial(n):
    return 1 if n == 0 else n * factorial(n-1)

factorial(5)

120

In [ ]:
def count_vowels(text):
  vowel_counter = 0
  for item in ['a' , 'e' , 'i' , 'o' , 'u']:
    if item in text:
      vowel_counter += 1
  return vowel_counter

count_vowels('abcaeidei')

3

**Python Libraries for Data Science**

  - Numpy
  - Pandas
  - Matplotlib

In [ ]:
x = 4
print(x * 3)

12


In [ ]:
y = [3,2,1,6,9,2]
print(y * 3)

[3, 2, 1, 6, 9, 2, 3, 2, 1, 6, 9, 2, 3, 2, 1, 6, 9, 2]


**Numpy** - Perform numerical operations on multi-dimensional data

In [ ]:
#pip install numpy

In [ ]:
import numpy as np

n1 = np.array([3,2,5,1,6])
print(n1)

[3 2 5 1 6]


In [ ]:
print(n1 * 2)

[ 6  4 10  2 12]


In [ ]:
n2 = np.array([[6,9,4,3,2],[2,3,5,1,7],[5,1,7,2,1]])
print(n2)

[[6 9 4 3 2]
 [2 3 5 1 7]
 [5 1 7 2 1]]


In [ ]:
print(n2 * 3)

[[18 27 12  9  6]
 [ 6  9 15  3 21]
 [15  3 21  6  3]]


In [ ]:
print(n1)

[3 2 5 1 6]


In [ ]:
print(n1.shape)
print(n1.ndim)

(5,)
1


In [ ]:
print(n2)

[[6 9 4 3 2]
 [2 3 5 1 7]
 [5 1 7 2 1]]


In [ ]:
print(n2.shape)
print(n2.ndim)

(3, 5)
2


In [ ]:
print(n2)

[[6 9 4 3 2]
 [2 3 5 1 7]
 [5 1 7 2 1]]


In [ ]:
print(np.mean(n2))
print(np.min(n2))
print(np.max(n2))
print(np.sum(n2))
print(np.std(n2))
print(np.var(n2))
print(np.argmin(n2))
print(np.argmax(n2))

3.8666666666666667
1
9
58
2.4458581770458854
5.982222222222222
8
1


In [ ]:
print(n2)

[[6 9 4 3 2]
 [2 3 5 1 7]
 [5 1 7 2 1]]


In [ ]:
print(np.mean(n2 , axis = 0))
print(np.min(n2 ,  axis = 0))
print(np.max(n2 , axis = 0))
print(np.sum(n2 , axis = 0))
print(np.std(n2 , axis = 0))
print(np.var(n2 , axis = 0))
print(np.argmin(n2 , axis = 0))
print(np.argmax(n2 , axis = 0))

[4.33333333 4.33333333 5.33333333 2.         3.33333333]
[2 1 4 1 1]
[6 9 7 3 7]
[13 13 16  6 10]
[1.69967317 3.39934634 1.24721913 0.81649658 2.62466929]
[ 2.88888889 11.55555556  1.55555556  0.66666667  6.88888889]
[1 2 0 1 2]
[0 0 2 0 1]


In [ ]:
print(n2)

[[6 9 4 3 2]
 [2 3 5 1 7]
 [5 1 7 2 1]]


In [ ]:
print(np.mean(n2 , axis = 1))
print(np.min(n2 ,  axis = 1))
print(np.max(n2 , axis = 1))
print(np.sum(n2 , axis = 1))
print(np.std(n2 , axis = 1))
print(np.var(n2 , axis = 1))
print(np.argmin(n2 , axis = 1))
print(np.argmax(n2 , axis = 1))

[4.8 3.6 3.2]
[2 1 1]
[9 7 7]
[24 18 16]
[2.48193473 2.15406592 2.4       ]
[6.16 4.64 5.76]
[4 3 1]
[1 4 2]


In [ ]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = np.array([[2,3,5,9,1] , [1,7,9,3,8] , [4,3,8,2,1]])
print(a)

[[2 3 5 9 1]
 [1 7 9 3 8]
 [4 3 8 2 1]]


In [ ]:
b = np.array([[4,1,2,3,5],[2,1,9,8,7]])
print(b)

[[4 1 2 3 5]
 [2 1 9 8 7]]


**Stacking**

In [ ]:
print(np.vstack((a,b)))

[[2 3 5 9 1]
 [1 7 9 3 8]
 [4 3 8 2 1]
 [4 1 2 3 5]
 [2 1 9 8 7]]


In [ ]:
c = np.array([[2,3],[5,4],[1,9]])
print(c)

[[2 3]
 [5 4]
 [1 9]]


In [ ]:
print(np.hstack((a,c)))

[[2 3 5 9 1 2 3]
 [1 7 9 3 8 5 4]
 [4 3 8 2 1 1 9]]


**Slicing**

In [ ]:
print(a)

[[2 3 5 9 1]
 [1 7 9 3 8]
 [4 3 8 2 1]]


In [ ]:
#array[row_index,column_index]
print(a[0,0])
print(a[1,3])

2
3


In [ ]:
#array[initial_index : initial_index + number_of_steps]

a1 = np.array([3,2,5,1,6,7,8,9,2,5,4,6,7,2,0])
print(a1)
print(a1[3:9])
print(a1[8:13])
print(a1[-3:])

[3 2 5 1 6 7 8 9 2 5 4 6 7 2 0]
[1 6 7 8 9 2]
[2 5 4 6 7]
[7 2 0]


In [ ]:
a2 = np.array([[2,3,2,1,5,6,7,8] , [12,13,12,11,15,16,17,18] ,
 [21,31,21,11,51,61,71,81] , [22,32,22,12,52,26,27,28] , [32,33,32,31,53,63,73,83]])
print(a2)

[[ 2  3  2  1  5  6  7  8]
 [12 13 12 11 15 16 17 18]
 [21 31 21 11 51 61 71 81]
 [22 32 22 12 52 26 27 28]
 [32 33 32 31 53 63 73 83]]


In [ ]:
print(a2[1:4 , 2:6])

[[12 11 15 16]
 [21 11 51 61]
 [22 12 52 26]]


In [ ]:
print(a2[:,7:8])

[[ 8]
 [18]
 [81]
 [28]
 [83]]


In [ ]:
print(a2[:,-1:])

[[ 8]
 [18]
 [81]
 [28]
 [83]]


In [ ]:
print(a2[:,-2:])

[[ 7  8]
 [17 18]
 [71 81]
 [27 28]
 [73 83]]


In [ ]:
print(a2)

[[ 2  3  2  1  5  6  7  8]
 [12 13 12 11 15 16 17 18]
 [21 31 21 11 51 61 71 81]
 [22 32 22 12 52 26 27 28]
 [32 33 32 31 53 63 73 83]]


In [ ]:
print(a2[-1,:])

[32 33 32 31 53 63 73 83]
